# Generated by Django 4.2.1 on 2023-06-01 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('HRmanage', '0002_delete_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayOffDep',
            fields=[
                ('year', models.IntegerField(primary_key=True, serialize=False)),
                ('RestDay', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='checkin',
            name='checkin',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='checkin',
            name='checkout',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='project',
            name='principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HRmanage.employee'),
        ),
    ]
